//
// This is the grammar specification from the Final Draft of the generic spec.
//
////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007 IBM Corporation.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
//
//Contributors:
//    Philippe Charles (pcharles@us.ibm.com) - initial API and implementation

////////////////////////////////////////////////////////////////////////////////

namespace LpgJava
{

public interface JavaParsersym {
    public const int
      TK_ClassBodyDeclarationsoptMarker = 100,
      TK_LPGUserActionMarker = 101,
      TK_IntegerLiteral = 31,
      TK_LongLiteral = 32,
      TK_FloatingPointLiteral = 33,
      TK_DoubleLiteral = 34,
      TK_CharacterLiteral = 35,
      TK_StringLiteral = 36,
      TK_MINUS_MINUS = 23,
      TK_OR = 89,
      TK_MINUS = 44,
      TK_MINUS_EQUAL = 71,
      TK_NOT = 49,
      TK_NOT_EQUAL = 90,
      TK_REMAINDER = 82,
      TK_REMAINDER_EQUAL = 72,
      TK_AND = 73,
      TK_AND_AND = 91,
      TK_AND_EQUAL = 74,
      TK_LPAREN = 1,
      TK_RPAREN = 5,
      TK_MULTIPLY = 68,
      TK_MULTIPLY_EQUAL = 75,
      TK_COMMA = 42,
      TK_DOT = 41,
      TK_DIVIDE = 83,
      TK_DIVIDE_EQUAL = 76,
      TK_COLON = 52,
      TK_SEMICOLON = 4,
      TK_QUESTION = 92,
      TK_AT = 3,
      TK_LBRACKET = 20,
      TK_RBRACKET = 53,
      TK_XOR = 93,
      TK_XOR_EQUAL = 77,
      TK_LBRACE = 29,
      TK_OR_OR = 102,
      TK_OR_EQUAL = 78,
      TK_RBRACE = 47,
      TK_TWIDDLE = 50,
      TK_PLUS = 45,
      TK_PLUS_PLUS = 24,
      TK_PLUS_EQUAL = 79,
      TK_LESS = 25,
      TK_LEFT_SHIFT = 69,
      TK_LEFT_SHIFT_EQUAL = 80,
      TK_LESS_EQUAL = 84,
      TK_EQUAL = 51,
      TK_EQUAL_EQUAL = 94,
      TK_GREATER = 48,
      TK_GREATER_EQUAL = 112,
      TK_RIGHT_SHIFT = 113,
      TK_RIGHT_SHIFT_EQUAL = 114,
      TK_UNSIGNED_RIGHT_SHIFT = 115,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 116,
      TK_ELLIPSIS = 103,
      TK_BeginAction = 104,
      TK_EndAction = 105,
      TK_BeginJava = 106,
      TK_EndJava = 107,
      TK_NoAction = 108,
      TK_NullAction = 109,
      TK_BadAction = 110,
      TK_abstract = 26,
      TK_assert = 56,
      TK_boolean = 7,
      TK_break = 57,
      TK_byte = 8,
      TK_case = 70,
      TK_catch = 95,
      TK_char = 9,
      TK_class = 40,
      TK_const = 117,
      TK_continue = 58,
      TK_default = 66,
      TK_do = 59,
      TK_double = 10,
      TK_enum = 43,
      TK_else = 85,
      TK_extends = 81,
      TK_false = 37,
      TK_final = 15,
      TK_finally = 96,
      TK_float = 11,
      TK_for = 60,
      TK_goto = 118,
      TK_if = 61,
      TK_implements = 111,
      TK_import = 97,
      TK_instanceof = 86,
      TK_int = 12,
      TK_interface = 17,
      TK_long = 13,
      TK_native = 54,
      TK_new = 27,
      TK_null = 38,
      TK_package = 98,
      TK_private = 21,
      TK_protected = 22,
      TK_public = 16,
      TK_return = 62,
      TK_short = 14,
      TK_static = 18,
      TK_strictfp = 30,
      TK_super = 19,
      TK_switch = 63,
      TK_synchronized = 46,
      TK_this = 28,
      TK_throw = 64,
      TK_throws = 99,
      TK_transient = 87,
      TK_true = 39,
      TK_try = 65,
      TK_void = 6,
      TK_volatile = 88,
      TK_while = 55,
      TK_EOF_TOKEN = 67,
      TK_IDENTIFIER = 2,
      TK_ERROR_TOKEN = 119;

    public static string[] orderedTerminalSymbols = {
                 "",
                 "LPAREN",
                 "IDENTIFIER",
                 "AT",
                 "SEMICOLON",
                 "RPAREN",
                 "void",
                 "boolean",
                 "byte",
                 "char",
                 "double",
                 "float",
                 "int",
                 "long",
                 "short",
                 "final",
                 "public",
                 "interface",
                 "static",
                 "super",
                 "LBRACKET",
                 "private",
                 "protected",
                 "MINUS_MINUS",
                 "PLUS_PLUS",
                 "LESS",
                 "abstract",
                 "new",
                 "this",
                 "LBRACE",
                 "strictfp",
                 "IntegerLiteral",
                 "LongLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "false",
                 "null",
                 "true",
                 "class",
                 "DOT",
                 "COMMA",
                 "enum",
                 "MINUS",
                 "PLUS",
                 "synchronized",
                 "RBRACE",
                 "GREATER",
                 "NOT",
                 "TWIDDLE",
                 "EQUAL",
                 "COLON",
                 "RBRACKET",
                 "native",
                 "while",
                 "assert",
                 "break",
                 "continue",
                 "do",
                 "for",
                 "if",
                 "return",
                 "switch",
                 "throw",
                 "try",
                 "default",
                 "EOF_TOKEN",
                 "MULTIPLY",
                 "LEFT_SHIFT",
                 "case",
                 "MINUS_EQUAL",
                 "REMAINDER_EQUAL",
                 "AND",
                 "AND_EQUAL",
                 "MULTIPLY_EQUAL",
                 "DIVIDE_EQUAL",
                 "XOR_EQUAL",
                 "OR_EQUAL",
                 "PLUS_EQUAL",
                 "LEFT_SHIFT_EQUAL",
                 "extends",
                 "REMAINDER",
                 "DIVIDE",
                 "LESS_EQUAL",
                 "else",
                 "instanceof",
                 "transient",
                 "volatile",
                 "OR",
                 "NOT_EQUAL",
                 "AND_AND",
                 "QUESTION",
                 "XOR",
                 "EQUAL_EQUAL",
                 "catch",
                 "finally",
                 "import",
                 "package",
                 "throws",
                 "ClassBodyDeclarationsoptMarker",
                 "LPGUserActionMarker",
                 "OR_OR",
                 "ELLIPSIS",
                 "BeginAction",
                 "EndAction",
                 "BeginJava",
                 "EndJava",
                 "NoAction",
                 "NullAction",
                 "BadAction",
                 "implements",
                 "GREATER_EQUAL",
                 "RIGHT_SHIFT",
                 "RIGHT_SHIFT_EQUAL",
                 "UNSIGNED_RIGHT_SHIFT",
                 "UNSIGNED_RIGHT_SHIFT_EQUAL",
                 "const",
                 "goto",
                 "ERROR_TOKEN"
             };

    public const int numTokenKinds = 120;
    public const bool isValidForParser = true;
}}
